"""pptchartengine

Core editable PowerPoint chart engine extracted from `ppt-st`.

Scope:
- native editable combo charts in `.pptx`
- dual-axis financial time-series charts
- date-axis presets
- chart parsing and cleanup helpers
- finance preset configs for common pension/investment charts
"""

from .api import create_combo_chart
from .cleaner import ChartJunkCleaner, clean_chart
from .date_axis import (
    BIWEEKLY_TICKS,
    DAILY_TICKS,
    MONTHLY_TICKS,
    QUARTERLY_TICKS,
    WEEKLY_TICKS,
    YEARLY_TICKS,
    DateAxisConfig,
)
from .layout import (
    DEFAULT_CATEGORY_AXIS_CONFIG,
    DEFAULT_LEGEND_CONFIG,
    DEFAULT_VALUE_AXIS_CONFIG,
    CategoryAxisConfig,
    ChartLayoutConfig,
    LegendConfig,
    ValueAxisConfig,
)
from .annotations import (
    add_value_labels,
    apply_annotations,
    apply_forecast_pattern,
    highlight_category,
)
from .examples import SCENARIO_EXAMPLES, chart_spec_examples
from .parser import (
    ChartParser,
    parse_all_charts_from_pptx,
    parse_all_semantic_components_from_pptx,
    parse_chart_from_pptx,
    parse_semantic_component_from_pptx,
)
from .range_chart import create_range_chart
from .schema import chart_spec_schema
from .spec import (
    NormalizedSpec,
    SpecError,
    chart_spec_reference,
    normalize_spec,
    render_chart,
    validate_spec,
)
from .presets import (
    CHART_PRESET_FUNCTIONS,
    FINANCE_PRESET_FUNCTIONS,
    RANGE_SNAPSHOT_PRESET_FUNCTIONS,
    VERTICAL_VALUATION_PRESET_FUNCTIONS,
    build_range_snapshot_preset,
    get_asx200_sector_valuation_snapshot_preset,
    get_chart1_config,
    get_chart2_config,
    get_chart3_config,
    get_chart4_config,
    get_chart_config,
    get_msci_emu_sector_valuation_snapshot_preset,
    get_msci_japan_sector_valuation_snapshot_preset,
    get_sp500_sector_valuation_snapshot_preset,
    get_vertical_global_valuation_snapshot_preset,
    get_vertical_sector_valuation_snapshot_preset,
)
from .styles import (
    COLOR_SCHEMES,
    DEFAULT_STYLE_CONFIG,
    DARK_BLUE,
    DARK_GRAY,
    DARK_ORANGE,
    DARK_RED,
    LIGHT_BLUE,
    LIGHT_GRAY,
    LIGHT_ORANGE,
    LIGHT_RED,
    StyleConfig,
)
from .tokens import (
    CHART_TOKENS,
    CHART_PALETTE_TOKENS,
    register_scheme,
    register_schemes,
    get_scheme,
    list_schemes,
    set_chart_tokens,
    get_chart_token,
    get_chart_palette,
    reset_tokens,
)
from .scatter import (
    ScatterParseResult,
    create_bubble_chart,
    create_scatter_chart,
    parse_bubble_chart,
    parse_bubble_from_pptx,
    parse_scatter_chart,
    parse_scatter_from_pptx,
)
from .range_snapshot import (
    RangeSnapshotParseResult,
    build_range_snapshot_spec,
    create_range_snapshot_chart,
    get_range_snapshot_spec,
    parse_range_snapshot_chart,
    parse_range_snapshot_from_pptx,
    prepare_range_snapshot_dataframe,
    restore_range_snapshot_dataframe,
)
from .waterfall import (
    WaterfallParseResult,
    build_waterfall_spec,
    create_waterfall_chart,
    get_waterfall_spec,
    parse_waterfall_chart,
    parse_waterfall_from_pptx,
    prepare_waterfall_dataframe,
    restore_waterfall_dataframe,
)
from .semantic_family import (
    ATTRIBUTION_DECOMPOSITION_FAMILY,
    AWARD_TIMELINE_PANEL_FAMILY,
    CONCENTRATION_FAMILY,
    DISTRIBUTION_PLUS_HISTORY_FAMILY,
    DUAL_CHART_PANEL_FAMILY,
    EVENT_TIMELINE_FAMILY,
    FACTOR_EXPOSURE_FAMILY,
    FACTOR_ATTRIBUTION_PANEL_FAMILY,
    HEATMAP_MATRIX_FAMILY,
    HOLDING_DETAIL_FAMILY,
    MANAGER_TIMELINE_PROFILE_FAMILY,
    PERFORMANCE_COMPARE_FAMILY,
    REGIME_TABLE_PANEL_FAMILY,
    RANKED_TILE_MATRIX_FAMILY,
    SCORE_OVERLAY_FAMILY,
    SEMANTIC_FAMILY_REGISTRY,
    SELECTION_TIMING_GRID_FAMILY,
    STYLE_ALLOCATION_FAMILY,
    STYLE_BOX_FAMILY,
    TABLE_PLUS_CHART_COMPOSITE_FAMILY,
    SemanticChartParseResult,
    create_attribution_decomposition_chart,
    create_concentration_chart,
    create_distribution_history_chart,
    create_distribution_snapshot_chart,
    create_dual_chart_panel,
    create_event_timeline_chart,
    create_factor_exposure_chart,
    create_factor_attribution_panel,
    create_award_timeline_panel,
    create_heatmap_matrix_chart,
    create_holding_detail_panel,
    create_manager_timeline_profile,
    create_performance_compare_chart,
    create_regime_table_panel,
    create_ranked_tile_matrix_chart,
    create_score_overlay_chart,
    create_semantic_chart,
    create_selection_timing_grid,
    create_style_allocation_chart,
    create_style_box_chart,
    create_table_plus_chart_composite,
    get_semantic_chart_spec,
    list_semantic_families,
    parse_semantic_chart_from_layout_info,
)

from .inspect import (
    ChartInventoryItem,
    ChartSelector,
    inspect_pptx_charts,
)
from .metadata import (
    METADATA_SCHEMA_VERSION,
    METADATA_SHEET_NAME,
    ChartMetadataV1,
    write_chart_metadata,
)
from .replace import (
    ReplaceResult,
    SeriesData,
    replace_pptx_chart_data,
)

__version__ = "0.1.0"

__all__ = [
    "BIWEEKLY_TICKS",
    "CHART_PRESET_FUNCTIONS",
    "COLOR_SCHEMES",
    "CHART_TOKENS",
    "CHART_PALETTE_TOKENS",
    "register_scheme",
    "register_schemes",
    "get_scheme",
    "list_schemes",
    "set_chart_tokens",
    "get_chart_token",
    "get_chart_palette",
    "reset_tokens",
    "ChartJunkCleaner",
    "ChartLayoutConfig",
    "ChartParser",
    "CategoryAxisConfig",
    "DAILY_TICKS",
    "DEFAULT_CATEGORY_AXIS_CONFIG",
    "DEFAULT_LEGEND_CONFIG",
    "DEFAULT_STYLE_CONFIG",
    "DEFAULT_VALUE_AXIS_CONFIG",
    "DARK_BLUE",
    "DARK_GRAY",
    "DARK_ORANGE",
    "DARK_RED",
    "DateAxisConfig",
    "FINANCE_PRESET_FUNCTIONS",
    "LIGHT_BLUE",
    "LIGHT_GRAY",
    "LIGHT_ORANGE",
    "LIGHT_RED",
    "LegendConfig",
    "MONTHLY_TICKS",
    "NormalizedSpec",
    "QUARTERLY_TICKS",
    "RANGE_SNAPSHOT_PRESET_FUNCTIONS",
    "SpecError",
    "VERTICAL_VALUATION_PRESET_FUNCTIONS",
    "StyleConfig",
    "chart_spec_examples",
    "chart_spec_schema",
    "chart_spec_reference",
    "SCENARIO_EXAMPLES",
    "normalize_spec",
    "render_chart",
    "validate_spec",
    "ValueAxisConfig",
    "WEEKLY_TICKS",
    "YEARLY_TICKS",
    "add_value_labels",
    "apply_annotations",
    "apply_forecast_pattern",
    "ATTRIBUTION_DECOMPOSITION_FAMILY",
    "AWARD_TIMELINE_PANEL_FAMILY",
    "CONCENTRATION_FAMILY",
    "DISTRIBUTION_PLUS_HISTORY_FAMILY",
    "DUAL_CHART_PANEL_FAMILY",
    "EVENT_TIMELINE_FAMILY",
    "FACTOR_EXPOSURE_FAMILY",
    "FACTOR_ATTRIBUTION_PANEL_FAMILY",
    "HEATMAP_MATRIX_FAMILY",
    "HOLDING_DETAIL_FAMILY",
    "MANAGER_TIMELINE_PROFILE_FAMILY",
    "PERFORMANCE_COMPARE_FAMILY",
    "REGIME_TABLE_PANEL_FAMILY",
    "RANKED_TILE_MATRIX_FAMILY",
    "SCORE_OVERLAY_FAMILY",
    "SEMANTIC_FAMILY_REGISTRY",
    "SELECTION_TIMING_GRID_FAMILY",
    "STYLE_ALLOCATION_FAMILY",
    "STYLE_BOX_FAMILY",
    "TABLE_PLUS_CHART_COMPOSITE_FAMILY",
    "SemanticChartParseResult",
    "clean_chart",
    "create_attribution_decomposition_chart",
    "create_bubble_chart",
    "create_combo_chart",
    "create_concentration_chart",
    "create_distribution_history_chart",
    "create_distribution_snapshot_chart",
    "create_dual_chart_panel",
    "create_event_timeline_chart",
    "create_factor_exposure_chart",
    "create_factor_attribution_panel",
    "create_award_timeline_panel",
    "create_heatmap_matrix_chart",
    "create_holding_detail_panel",
    "create_manager_timeline_profile",
    "create_performance_compare_chart",
    "create_range_chart",
    "create_regime_table_panel",
    "create_ranked_tile_matrix_chart",
    "create_scatter_chart",
    "create_score_overlay_chart",
    "create_semantic_chart",
    "create_selection_timing_grid",
    "create_style_allocation_chart",
    "create_style_box_chart",
    "create_table_plus_chart_composite",
    "highlight_category",
    "get_chart1_config",
    "get_chart2_config",
    "get_chart3_config",
    "get_chart4_config",
    "get_chart_config",
    "build_range_snapshot_preset",
    "get_asx200_sector_valuation_snapshot_preset",
    "get_vertical_global_valuation_snapshot_preset",
    "get_vertical_sector_valuation_snapshot_preset",
    "get_sp500_sector_valuation_snapshot_preset",
    "get_msci_emu_sector_valuation_snapshot_preset",
    "get_msci_japan_sector_valuation_snapshot_preset",
    "get_semantic_chart_spec",
    "list_semantic_families",
    "parse_bubble_chart",
    "parse_bubble_from_pptx",
    "parse_all_charts_from_pptx",
    "parse_all_semantic_components_from_pptx",
    "parse_chart_from_pptx",
    "parse_semantic_component_from_pptx",
    "parse_semantic_chart_from_layout_info",
    "parse_scatter_chart",
    "parse_scatter_from_pptx",
    "ScatterParseResult",
    "build_range_snapshot_spec",
    "create_range_snapshot_chart",
    "get_range_snapshot_spec",
    "prepare_range_snapshot_dataframe",
    "restore_range_snapshot_dataframe",
    "parse_range_snapshot_chart",
    "parse_range_snapshot_from_pptx",
    "RangeSnapshotParseResult",
    "build_waterfall_spec",
    "create_waterfall_chart",
    "get_waterfall_spec",
    "prepare_waterfall_dataframe",
    "restore_waterfall_dataframe",
    "parse_waterfall_chart",
    "parse_waterfall_from_pptx",
    "WaterfallParseResult",
    # ADR-0007 §1 — inspect lifecycle (ADR-0006 §1)
    "ChartInventoryItem",
    "ChartSelector",
    "inspect_pptx_charts",
    # ADR-0007 §1 — metadata lifecycle (ADR-0004 §2 + ADR-0007 §3)
    "ChartMetadataV1",
    "METADATA_SCHEMA_VERSION",
    "METADATA_SHEET_NAME",
    "write_chart_metadata",
    # ADR-0007 §1 — replace lifecycle (ADR-0006 §2)
    "ReplaceResult",
    "SeriesData",
    "replace_pptx_chart_data",
]
